name: Unit Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: s3iofs-unit-tests-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: Unit Tests
    strategy:
      matrix:
        go-version: ["1.20"]
        platform: ["ubuntu-latest"]

    runs-on: ${{ matrix.platform }}
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - run: go mod download
      - run: go build -v .

      - name: Run linters
        uses: golangci/golangci-lint-action@639cd343e1d3b897ff35927a75193d57cfcba299 # v3.6.0
        with:
          version: latest

      - name: Install tparse
        run: go install github.com/mfridman/tparse@latest

      - name: Test
        env:
          COVER_OPTS: "-coverprofile=coverage.txt -covermode=atomic"
          GOFLAGS:  "-v -count=1 -json"
        run: go test $COVER_OPTS ./... | tparse -all -notests -format markdown >> $GITHUB_STEP_SUMMARY

      - name: Run Integration Tests
        run: go test -v ./...
        working-directory: integration
